def título(txt):
    print('-'*30)
    print(txt)
    print('-'*30)
#Programa Principal
# print('-'*30)
# lin()
# print("     CURSO EM VÍDEO    ")
# # print('-'*30)
# lin()
# # print('-'*30)
# lin()
# print("     APRENDA PYTHON    ")
# # print('-'*30)
# lin()
# lin()
# # print('-'*30)
# print("     GUSTAVO GUANABARA    ")
# # print('-'*30)
# lin()

título = ('   CURSO EM VÍDEO    ')
título = ('   APRENDA PYTHON    ')
título = ('   GUSTAVO GUANABARA    ')